### ISSUE TITLE
Prepare for "public release/announcement"

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#104]
could have been a project and separate issues but IMHO we do not have too many items for this.  

- [x] add (ana)conda badge  to README.md
- [x] may be add some brief HOWTO with a cron job example recipe? (flock etc)
- [ ] prepare "real-life" sample collections of logs/artifacts 
    - [x] https://github.com/con/tinuous-inception
    - [ ] datalad/datalad -- probably also just top level public and the rest not (I am still paranoid about possibly leaking some sensitive data "permanently")
    - [ ] datalad/git-annex -- will have top level dataset public with releases, but logs per month not public
    - any other you might be interested to add @jwodder ? (we have one for dandi-cli but not sure if worth sharing publicly, not that special/interesting one)
 - [x] cut a release after all those working as desire
 - [ ] adjust opening of README.md to
    - [ ] provide motivation (why bother)
    - [ ] point to those exemplar samples

WDYT anything else @jwodder ? (feel free to modify in-place)

**Comment by jwodder** [comment]
> add (ana)conda badge to README.md

I see several badges in [the conda-forge repo README](https://github.com/conda-forge/tinuous-feedstock/blob/master/README.md).  Do you mean the one under "Name" or the one under "Version"?

**Comment by yarikoptic** [comment]
I meant to add the one from conda-forge README.md, this one if I selected right
```
[![Conda Version](https://img.shields.io/conda/vn/conda-forge/tinuous.svg)](https://anaconda.org/conda-forge/tinuous) 
```
to README.md in this repo near the pypi one.

**Comment by yarikoptic** [comment]
please point to the continuous-inception in the README, and we have badges now (thanks), and I did already announce in some media, so we could then consider this one "dealt with".  Not yet sure if I will be posting any other demo repos.
