### ISSUE TITLE
Add support for circle-ci

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#124]
e.g. for dandi-api which still uses it.

**Comment by yarikoptic** [comment]
Actually I don't know if dandi-archive uses circle-ci any longer. Current target is https://github.com/bids-standard/bids-specification/ .  Do you need to be "added" to get Read-only access ?

**Comment by jwodder** [comment]
@yarikoptic I can access at least some part of the API for that project.  I'll let you know if anything seems to require being added.

**Comment by yarikoptic** [comment]
are you logged in via github there or have some dedicated different login?

**Comment by yarikoptic** [comment]
I will request addition of you to bids-standard but may be meanwhile could create some primitive setup for testing https://github.com/con/tinuous-inception to iron support on?

**Comment by yarikoptic** [comment]
right -- add circle-ci to tinuous (as we did for travis/appveyor etc) so tinuous-inception could fetch them "as a test".

**Comment by jwodder** [comment]
@yarikoptic I sent you (I assume) a request to enable Circle CI for the "con" organization.

**Comment by jwodder** [comment]
@yarikoptic Here's what I've found & figured out about fetching Circle CI logs so far:

* Circle CI has two versions of its API, v1.1 and v2.  A notice at the top of the v1.1 docs states "v1 APIs will be deprecated within the next year. We recommend switching to the v2 APIs."
* I cannot find a way to get logs via the v2 API
* [This post](https://discuss.circleci.com/t/api-to-get-raw-logs-for-a-job/40564) describes a way to get logs via the v1.1 API, but trying that led me to an S3 URL with an empty response body.
* By inspecting the URLs of the logs links in the web interface, I determined that I can get the logs for a step via the v1.1 API by making a request to `/api/v1.1/project/github/:org/:name/:build_num/output/:step/0?file=true`.  I'm not sure of the meaning of the `/0` at the end, but I think it may have to do with parallel runs.

**Comment by jwodder** [comment]
@yarikoptic Question posted: https://discuss.circleci.com/t/downloading-build-logs-with-v2-api/44780

**Comment by yarikoptic** [comment]
so far it seems boils down to use v1.1 API for now

**Comment by yarikoptic** [comment]
there were answers on https://discuss.circleci.com/t/downloading-build-logs-with-v2-api/44780/3 . @jwodder - are they sufficient to get this feature implemented?

**Comment by jwodder** [comment]
@yarikoptic Those told me nothing I didn't already know.  The situation remains the same as before: logs can currently only be downloaded via the v1 API, which is slated for removal.

**Comment by yarikoptic** [comment]
it seems that only 1 step requires v1 api , the others could be done via v2.  So let's get it implemented via v2+v1 mix. It should be trivial to redo one step via v2 whenever time comes.

**Comment by yarikoptic** [comment]
ping on this @jwodder -- one more project I would have loved to archive logs for is afni, in particular in the wakes of https://github.com/afni/afni/issues/466 and alike so I could see when regressions happened etc.
