### ISSUE TITLE
missing logs for the release github workflow for datalad?

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#160]
I thought to provide some details to clarify on https://github.com/nedbat/scriv/issues/82 but I seems can't find a log for the run of release workflow in our "archives" for DataLad:

- workflow is named 
```shell
❯ head -n 1 .github/workflows/release.yml
name: Auto-release on PR merge
```
- we have release on Jan 16th, and here is the most recent commits there:
```shell
❯ git lg 0.18.1 | head -n3
* cacf54d5b - (tag: 0.18.1) [skip ci] Update docs/source/changelog.rst (3 weeks ago) [DataLad Bot]
* ba31f0d2f - [skip ci] Update CHANGELOG (3 weeks ago) [DataLad Bot]
*   5649c5455 - Merge pull request #7250 from bpoldrack/pull-buffer-patch (3 weeks ago) [Benjamin Poldrack]
```
where last two are produced by release action.
- but there is no `*release*` named log anywhere in Jan:
```shell
(git)smaug:/mnt/datasets/datalad/ci/logs/2023/01[master]git
$> find -iname *release*
$>
```

- and for that date/commit we have only following ones:
```shell
(git)smaug:/mnt/datasets/datalad/ci/logs/2023/01[master]16/push/maint/5649c54
$> ls
appveyor-9094-failed/            github-Extensions-6098-success/               github-Type-check-779-success/
appveyor-9094-success/           github-Linters-2985-success/                  travis-15185-success/
github-Benchmarks-6090-success/  github-Shellcheck\ on\ scripts-4337-success/
github-Docs-6149-success/        github-Test\ on\ macOS-4326-success/
```

so seems nothing "Release" like was logged.  I guess we manage to miss such types (`on.pull_request_target` triggered?) entirely?

**Comment by jwodder** [comment]
@yarikoptic Where is the config for the tinuous job stored, and how do I access it?  As `jwodder@smaug`, I don't have permission for `/mnt/datasets/datalad/ci`, and can't log in as `dandi@smaug`.

**Comment by jwodder** [comment]
@yarikoptic Ping.

**Comment by yarikoptic** [comment]
login as `datalad@smaug` - I see your key allowed
