### ISSUE TITLE
interface to re-fetch logs for some specific PR

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#162]
in attempt to troubleshoot https://github.com/datalad/datalad/issues/7296 I thought to compare logs between to CI runs on that PR, for which we should have had logs on smaug a264136 and 2340b4c, for which we have

```
$> ls -ld */pr/7271/{a264136,2340b4c} 
drwxr-sr-x 1 datalad datalad 930 Feb 22 03:28 21/pr/7271/2340b4c/
drwxr-sr-x 1 datalad datalad 166 Feb 22 03:20 21/pr/7271/a264136/
drwxr-sr-x 1 datalad datalad  92 Feb 23 03:20 22/pr/7271/2340b4c/
```

<details>
<summary>placing the oddity of 1 fastest github run getting into 22nd aside</summary> 

```shell
(git)smaug:/mnt/datasets/datalad/ci/logs/2023/02[master]git
$> ls -l 22/pr/7271/2340b4c/ 21/pr/7271/2340b4c/
21/pr/7271/2340b4c/:
total 0
drwxr-sr-x 1 datalad datalad 280 Feb 22 03:28 appveyor-9134-failed/
drwxr-sr-x 1 datalad datalad 120 Feb 22 03:28 appveyor-9134-success/
drwxr-sr-x 1 datalad datalad  24 Feb 22 03:20 github-Add\ changelog.d\ snippet-565-incomplete/
drwxr-sr-x 1 datalad datalad  86 Feb 22 03:20 github-Benchmarks-6132-success/
drwxr-sr-x 1 datalad datalad  56 Feb 22 03:20 github-CrippledFS-3876-success/
drwxr-sr-x 1 datalad datalad  62 Feb 22 03:20 github-Docs-6191-success/
drwxr-sr-x 1 datalad datalad 648 Feb 22 03:20 github-Extensions-6140-failed/
drwxr-sr-x 1 datalad datalad  56 Feb 22 03:20 github-Linters-3027-success/
drwxr-sr-x 1 datalad datalad  56 Feb 22 03:20 github-Shellcheck\ on\ scripts-4379-success/
drwxr-sr-x 1 datalad datalad  56 Feb 22 03:20 github-Test\ for\ semver\ label-3182-success/
drwxr-sr-x 1 datalad datalad  56 Feb 22 03:20 github-Test\ old\ nose\ code-795-success/
drwxr-sr-x 1 datalad datalad 148 Feb 22 03:20 github-Test\ on\ macOS-4368-failed/
drwxr-sr-x 1 datalad datalad  68 Feb 22 03:20 github-Type-check-821-success/
drwxr-sr-x 1 datalad datalad  20 Feb 22 03:28 travis-15237-errored/
drwxr-sr-x 1 datalad datalad  70 Feb 22 03:28 travis-15237-failed/
drwxr-sr-x 1 datalad datalad  12 Feb 22 03:28 travis-15237-success/

22/pr/7271/2340b4c/:
total 0
drwxr-sr-x 1 datalad datalad 40 Feb 23 03:20 github-Auto-release\ on\ PR\ merge-325-incomplete/

```
</details>

what is most upsetting is that we have only few of non-interesting logs for the other one:

```shell
$> ls 21/pr/7271/a264136/
github-Add\ changelog.d\ snippet-564-success/  github-Test\ for\ semver\ label-3181-success/
```

AFAIK we do not have logs for those tinuous runs anywhere so can't tell why that happened (may be the idea of #154 would still have value). So I thought that may be there is a way to have a command to (re)fetch logs for some specific PR/commit?  @jwodder -- would that be possible?

**Comment by jwodder** [comment]
@yarikoptic 

* For GitHub, there's no direct way to get the workflow runs for a PR itself; instead, you have to go through the commits in the PR and fetch the associated runs for those.
* Travis and Appveyor do not appear to have a way to request the run(s) for a given PR or commit in the first place.

**Comment by yarikoptic** [comment]
rright -- commit is associated with a PR. So in principle I could request
"give me logs for commit X and place to folder Y", i.e. smth like `tinuous fetch-logs-for-commit a264136 21/pr/7271/a264136/` for my problem above?

**Comment by jwodder** [comment]
@yarikoptic Why would/should the output path be given on the command line?  Wouldn't it make more sense for it to be determined according to the config file as though it were being fetched as part of a normal tinuous run?

**Comment by yarikoptic** [comment]
the same commit , oddly enough, could be present in multiple PRs.  But ok -- could be without path specified.

**Comment by yarikoptic** [comment]
I keep running into use cases where I am thinking about having such a feature.
