### ISSUE TITLE
assist with identifying logs containing "sensitive" data

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#18]
not yet 100% sure if that should somehow should be a functionality of `tinuous` but I think it should.

Establish a collection of regular expressions to match complete strings/words in the logs which look like potential TOKENS and secret keys: 
- github, docker hub, appveyor, travis tokens
- AWS secret keys

Then `tinuous` could have an option `--allow-secrets` defaulting to empty (none are allowed), and allowing to say for which to not care. Then, if not allowed secret is detected, we raise an exception/exit non-0.  To help to avoid false positives we could add `--allow-secrets-regex` which could have lookback/ahead for fine tuned ignoring some specific "false positives".

Alternatively/complimentary -- we could also have option `--sanitize-secrets` which would replace those identified with placeholders, thus making it possible to share (sanitized) logs.

Rationale: I would like to post all datalad logs as pure git (not annex) repos, but fear that I might leak some sensitive information.

Also I wonder if `tinuous` could expose such functionality (detection and/or sanitization) so it could be ran on already collected logs (e.g. i could check if the logs I already have need to be sanitized etc).

**Comment by jwodder** [comment]
Best guesses at the respective regexes:

* GitHub tokens: `(v1\.)?[a-f0-9]{40}`
* Docker hub tokens: `[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}`
* Appveyor tokens: `(v2\.)?[a-z0-9]{20}`
* Travis tokens: `[a-zA-Z0-9]{22}`
* AWS secret keys: `[a-zA-Z0-9+/]{40}`

**Comment by yarikoptic** [comment]
Thanks!  so in some odd cases there might be some false positives (e.g. for travis) but I think it should be ok. `allow-secrets-regex` (probably not as a cmdline option, but rather in the config) should allow to whitelist some of those specific (long variable/attribute name etc)

**Comment by jwodder** [comment]
@yarikoptic 

> allow-secrets-regex (probably not as a cmdline option, but rather in the config) should allow to whitelist some of those specific (long variable/attribute name etc)

I'm not clear on what you're describing here.  Is this setting meant to be a regex for things that shouldn't be sanitized, or a list of strings that shouldn't be sanitized, or a list of names of secrets to not sanitize, or something else?

**Comment by yarikoptic** [comment]
a " regex for things that shouldn't be sanitized, ", e.g.  I could say that all `v1\.veryLongPrefix.*` are legit etc.

**Comment by jwodder** [comment]
Problem: GitHub tokens follow the same pattern as the SHA-1 hashes used for GitHub commits.  This makes trying to sanitize all possible GitHub tokens unwise.  (Also, the AWS secret pattern keeps matching portions of URLs and file paths.)

**Comment by yarikoptic** [comment]
:-( that sucks.  
- `github` I guess we should not enable github tokens matching then
- `docker hub` - didn't realize that it is matching a UUID. FTR: version 4 variant 9. e.g. (manually replace some with xxxs - might not match in number) `4cxxxxxx-xxxx-48d0-9375-dxxxxxxxxx` so regex could be restricted a bit but that is not a solution
- `AWS secret ` -- that sucks... since it is my primary fear I was trying to tame ... can you gimme examples on those matches?

**Comment by yarikoptic** [comment]
> * . can you gimme examples on those matches?

well, https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html gives an example which shows futility of my desire: `wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY` :-/ even though an exact match to be of 40 characters I hope is not too likely... also unlikely it would have some sensible word(s) in it -- I wonder if there is some heuristic which could be employed here... let me think

**Comment by jwodder** [comment]
@yarikoptic Example AWS secret false positive (Note: I put a `\b` at either end of the regex, hence why it's not matching at the beginning of the string): `/Users/appveyor/Library/Caches/Homebrew/nettle--3.6.catalina.bottle.tar.gz` gets sanitized to `/Users****************************************--3.6.catalina.bottle.tar.gz`

**Comment by yarikoptic** [comment]
;) thanks! I wonder if we define our custom "end of the word" which would not include `-` as delimiter (since I do not see likely for any secret to be concatenated with smth via `-`), and rather be a `['"\s\..;]` we could provide at least a partial remedy (although probably too weak one, so not sure if worth it)?

**Comment by yarikoptic** [comment]
more ad-hoc would be probably a heuristical analysis to say that something is actually a path, e.g. starts with a list of known leading directories known across OSes (like `/Users` here)?

**Comment by jwodder** [comment]
@yarikoptic Should the secret patterns be hardcoded into `tinuous` or supplied through the config file?  If the former, exactly which patterns are we still going with?  If the latter, should the `['"\s\.,;]` word boundary be the responsibility of the config file author, or should the script add that to the regexes automatically?

**Comment by yarikoptic** [comment]
I am thinking that hardcoding would be appropriate although we might reconsider (or just ask a config option for extra patterns) later eg discovering some project specific secrets such as dandi api tokens.

**Comment by yarikoptic** [comment]
Although since you already implemented via config in https://github.com/con/tinuous/pull/19/files - good with me.
