### ISSUE TITLE
add DataLad support and automagically create/save git submodules per e.g. month

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#21]
## DataLad

Should be present in the spec:
```
datalad: 
  enabled: true
  cfg_proc: text2git  # so `create(..., cfg='text2git')` is used
```
and if enabled, call `datalad create` whenever needed (see below) and `datalad save` upon finishing an update round (ideally with the commit message mentioning the stats - how many updates for each CI)

## subdatasets

I thought to do it on the level of datalad (by automating `save` creating such subdatasets: https://github.com/datalad/datalad/issues/5423), but I think it might be easier and better specified here even in the long run.
 
Specification probably should be achieved via use of `//` to annotate subdataset boundary, similarly to how we do in `datalad addurls`. E.g.
```
path: '{year}/{month}//{day}/{ci}/{type}/{type_id}/{commit}/{wf_name}/{number}/'
```
would say that each month would need a separate repository.  So whenever a new `month` is needed, `topds.create(f"{year}/{month}", cfg_proc="text2git")` before starting populating with logs, and then just `topds.save(recursive=True, message="... nice informative message with stats")`

**Comment by jwodder** [comment]
@yarikoptic To be clear: When `datalad.enabled` is set, you want the entire current directory to be treated as a Datalad dataset?  Should the script initialize that dataset, or should it assume that it's already initialized?  Also, is creating a new `Dataset` object every time a build log is processed efficient enough, or is the constructor so overhead-heavy that the instances should be cached?

**Comment by yarikoptic** [comment]
> @yarikoptic To be clear: When `datalad.enabled` is set, you want the entire current directory to be treated as a Datalad dataset? 

yes.  Which could also be a "super-dataset" in that it could have subdatasets (git submodules)

> Should the script initialize that dataset, or should it assume that it's already initialized?

I guess ideally it should be "turnkey", so to initialize it as well, but skip initialization if already a datalad dataset.

>  Also, is creating a new `Dataset` object every time a build log is processed efficient enough, or is the constructor so overhead-heavy that the instances should be cached?

`Dataset` object is flyweight pattern -- should be cheap, it should reuse a not yet gc-collected one if it existed prior for that path.

**Comment by jwodder** [comment]
@yarikoptic Initialization of the top-level dataset is likely to happen in a nonempty directory containing at least the `config.yml` file.  Should `force=True` be passed to the top-level `create()`?

**Comment by yarikoptic** [comment]
yes
