### ISSUE TITLE
cut release, upload to pypi and conda-forge

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#25]
After #24 and #23 PRs merged, let's cut initial release (0.1.0?) and upload for distribution
- [x] pypi
- [x] conda-forge

edit: I guess would need all setup.{cfg,py} which would install tineous script and versioneer for versioning?

**Comment by jwodder** [comment]
Uploaded to PyPI: https://pypi.org/project/tinuous/

**Comment by jwodder** [comment]
@yarikoptic conda-forge PR: https://github.com/conda-forge/staged-recipes/pull/14750 (Please indicate your willingness to be a maintainer)

**Comment by jwodder** [comment]
The conda-forge PR has been merged.
