### ISSUE TITLE
provide workaround for empty `pull_requests` for github workflow runs

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#28]
per discussion in the slack.

Re empty `pull_requests`: if post to support@github is available from some public'ish url please post it here @jwodder FTR

**Comment by jwodder** [comment]
@yarikoptic GitHub Support tickets appear to be private, but the contents of the ticket are as follows:

Posted by me on Jan 28:

> When retrieving information about a workflow run from the GitHub API, if the run was triggered by pull request activity, the `"pull_requests"` field will be non-empty if the associated PR is still open, but the field then becomes empty once the PR is merged or closed. This seems like a mistake, as it makes it seemingly impossible to reliably associate a run with its PR, and I know that GitHub still has the PR information for the run, as the information is still displayed in the Actions web interface. I would like to request that the `"pull_requests"` field of workflow run objects remain populated with closed & merged PRs.

Posted by a GitHub staff member on Jan 29:

> Hmm, I can reproduce this behavior with https://docs.github.com/en/rest/reference/actions#get-a-workflow-run after closing a pull request -- not sure if it's expected behavior or a bug but I'll go ahead and open an issue for our Actions folks about this. I can't promise a specific ETA but I'll make a note to followup with any news.
>
> As a side note, since we're opening an issue for another team this ticket will auto-close in a few days but you can always followup if you'd like.
