### ISSUE TITLE
Add abbrev_commit (first 7 chars of `commit`)

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#40]
In light of #39 and no need really to store full commit in the path.

BTW -- do we have access to other commit information (e.g. the datetime?) if we do, then having `commit_datetime` or alike would also be handy -- this would allow to have them in some sortable order within a PR or even a branch.

**Comment by jwodder** [comment]
@yarikoptic Aside from the commit hash, the commit information that all three CI systems provide (that tinuous doesn't already expose) are the commit message and the commit timestamp.
