### ISSUE TITLE
establish minimalistic testing

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#5]
I am thinking 
- add CI setups for all supported (travis, github actions, appveyor) with initial "test" is just installing dependencies and running `tinuous --help` (I already discovered that it doesn't work with python 3.7)
- make https://github.com/con/tinuous-inception  (or any other name) and make CI runs in master collect the output of tineous for this repo (probably would need somehow to skip "ongoing" runs)

**Comment by jwodder** [comment]
@yarikoptic Note that Appveyor is currently not supported, as I was having trouble getting the API to work.  A separate issue should be created for adding Appveyor support.

**Comment by jwodder** [comment]
https://github.com/con/tinuous-inception has been set up to fetch logs daily at midnight UTC.

**Comment by jwodder** [comment]
@yarikoptic I think you may need to activate this repository on Travis; https://travis-ci.com/github/con/tinuous is giving me a 404.

**Comment by yarikoptic** [comment]
I think I have succeeded! ;)

**Comment by jwodder** [comment]
@yarikoptic Yep, it's building now.  con/tinuous-inception should finally succeed tonight.

**Comment by jwodder** [comment]
con/tinuous-inception ran and contains the con/tinuous logs.
