### ISSUE TITLE
Support slicing of the fields, e.g. {commit[:8]} -- f-string's formatter

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#58]
IIRC `.format` allows for formatters. I had used those somewhat wildly in e.g. https://github.com/datalad/datalad-deprecated/blob/HEAD/datalad_deprecated/ls.py#L369 

I think allowing for a set of generic formatters which could be applied to any field would be useful and avoid exponential combinatorics while adding other entries (e.g. `{merge_commit}`).

Alternative for this particular one could still be to figure out how to get indexing work in there, so it could be `{commit[:8]}`

**Comment by jwodder** [comment]
@yarikoptic I don't believe indexing will work, as the code uses `format_map()`, not f-strings.

Should only `{commit}` and `{merge_commit}` be abbreviateable in this way, or should all fields be?

**Comment by yarikoptic** [comment]
> @yarikoptic I don't believe indexing will work, as the code uses `format_map()`, not f-strings.

formatters work with `.format_map`:
```
In [8]: "{a!r}".format_map(d)
Out[8]: "'1234567'"
```
and I believe that is what the code I pointed you to relies on being able to do (just straight via .format https://github.com/datalad/datalad-deprecated/blob/HEAD/datalad_deprecated/ls.py#L440)

> Should only {commit} and {merge_commit} be abbreviateable in this way, or should all fields be?

ATM those are immediate "use cases" indeed, so might indeed sound like an overkill ... dug a bit deeper -- it would be the subclass of `string.Formatter` which isn't really as good as `str.format()` so indeed not worth it.

BUT another idea came up -- may be there is a better way, but we can just use f-strings!  My ugly prototype:

```python
def fstring(s, **kwargs):
    return eval("f%r" % s, {}, kwargs)

print(fstring("{v[:3]}", v="1234"))
```
produces
```
$> python3 /tmp/123.py
123
```
so we could just use such helper if there is no native way to just access f-string's formatter. This should give us indexing.

**Comment by jwodder** [comment]
@yarikoptic The "native way to access f-string's formatter" (assuming you mean what I think) is to define a class with a custom `__format__` method for interpreting format specs like `!foo`, wrap it around the `commit` value, and pass that in the "commit" field to `.format_map()`.  This lets us define custom format specs, but it won't get us indexing.  Just how desperate are you for indexing?

**Comment by yarikoptic** [comment]
I just like to avoid duplicate `abbrev_` wherever we need to add one. Also with slicing/indexing people might tune it to their liking also for workflow files etc.

I am not sure if what you think is what I mean since it won't get us indexing.  I meant really smth like a python interface to what Python calls on `"s"` whenever it sees `f"s"`.

What do you dislike about my concise ad-hoc helper ;-) ?

**Comment by jwodder** [comment]
@yarikoptic The only thing I dislike about your helper is my natural wariness of any use of `eval()`.  It should be safe to use as shown here, though, so if you want to go that way to gain indexing, I'll do it.

**Comment by yarikoptic** [comment]
I don't like using `eval` either, but rarely I do get into cases where I see no other way and provides a very easy workaround.  Lets do it!
