### ISSUE TITLE
Make datalad an extra?

### ISSUE THREAD

**Issue by jwodder** [con/tinuous#61]
Seeing as our goal is to make this project useful to more than just us, and given how heavyweight datalad and its dependencies are and how optional it is for tinuous' functioning, I think that `datalad` should belong to a `[datalad]` extra of tinuous instead of being an unconditional dependency.  (I'm not sure how this would work out with conda-forge, though.)

@yarikoptic Thoughts?

**Comment by yarikoptic** [comment]
yes, I am all for it.  
May be right away add `[all]` which would ATM be just everything of `[datalad]`.  We do the same in datalad -- helps later with just knowing I can `pip install module[all]` to get as full installation as greedy me desires ;-)
