### ISSUE TITLE
github.workflows config: make it a glob or regex to allow for a more flexible selection

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#74]
Finally got to establish one for https://github.com/datalad/git-annex/tree/master/.github/workflows . There I would like to get all `build-*.yaml` (apparently we aren't consistent in extension, and have `build-prs.yml`) but ignore the other frequent ones for updates etc.  ATM I can only list them explicitly (which I will do for now) instead of somehow select via regex (seems might be the most flexible) or exclude undesired.  WDYT @jwodder ?

**Comment by jwodder** [comment]
@yarikoptic I can do that using either globs or regexen.  I just need to know exactly what the config structure should look like and, if we're reusing the `workflows` key, whether the old `workflows: [...]` structure should be maintained / how it should interact with any new keys.

**Comment by yarikoptic** [comment]
Can I just leave it up to you to decide one way or another?  I have not used `workflows` limiting AFAIK yet, so as to me we could just "break" and reuse workflows to be regexes (IMHO more flexible than globs), or we could add a new key `workflows_filter: str or list` which if specified would filter `workflows` (which are all if not specified).

**Comment by yarikoptic** [comment]
ATM just doing `include` would have been sufficient, but may be indeed could be `workflows_include: regex` and `workflows_exclude: regex`? (exclude to apply after include although doesn't matter much ;-) )
