### ISSUE TITLE
codecov is "semi working": doesn't provide status to PRs, reports "Unable to find commit in Github"

### ISSUE THREAD

**Issue by yarikoptic** [con/tinuous#90]
realized while looking at https://github.com/con/tinuous/pull/89/files that there is no codecov report.

https://app.codecov.io/gh/con/tinuous/branch/gh-88/commits?page=1 says "Unable to find commit in Github"  and
https://app.codecov.io/gh/con/tinuous/pulls?page=1&state=open&order=-pullid  has the last good one for "#66 Updated 9 days ago by jwodder" and then there is only 1 without title  and saying "Missing base report" .

Smells like codecov issue, but may be you feel that something on our end managed to break it about 9 days ago @jwodder ?

**Comment by yarikoptic** [comment]
hm, codecov commenter reemerged on https://github.com/con/tinuous/pull/89 but no status withing the matrix of CI reports

**Comment by jwodder** [comment]
@yarikoptic Did you set up this repo with [the Codecov app integration](https://github.com/apps/codecov) or some other integration?

**Comment by jwodder** [comment]
@yarikoptic This might have something to do with the fact that [the Travis builds](https://travis-ci.com/github/con/tinuous) seem to have stopped, which might be affecting Codecov's sense of whether CI is complete.

**Comment by yarikoptic** [comment]
HA -- I needed to explicitly (re?)choose Free plan on organizational settings on travis: https://travis-ci.com/organizations/con/plan?billingStep=3 . Then I triggered manually (! would be an interesting test case for con/tinuous ;)) a build on travis, which would have a commit but which shouldn't be pushed anyhow back to github, and that one seems to be building now
https://travis-ci.com/github/con/tinuous/builds/228647879

so let's see if that resolves travis + codecov situation

**Comment by yarikoptic** [comment]
nope, no codecov report for recent https://github.com/con/tinuous/pull/134 

codecov seems to have coverage: https://app.codecov.io/gh/con/tinuous  --> https://codecov.io/gh/con/tinuous/commit/8799d5ce48a23f94ca31d82a9776725dd17c6bb7/  and some banner suggests to install Codecov App!  installed for con (needs Read to admin part, which kinda strange), will accept my invaluable suggestion in that PR and see what happens

**Comment by yarikoptic** [comment]
I think it is "working" now
